services: 
  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./MySQL_DB:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/wp_admin_password
    env_file:
      - .env
    ports:
      - 3306:3306
    restart: "unless-stopped"
    secrets:
      - mysql_root_password
      - wp_admin_password
    networks:
      - defaultNet
  
  ldap:
    image: osixia/openldap
    container_name: ldap
    volumes:
      - ldap_conf:/etc/ldap/slapd.d
      - ldap_data:/var/lib/ldap
    environment:
      - LDAP_ADMIN_PASSWORD_FILE=/run/secrets/ldap_admin_password
      - LDAP_READONLY_USER_PASSWORD_FILE=/run/secrets/ldap_readonly_password
    env_file:
      - .env
    ports:
      - 389:389
      - 389:389/udp
      #- 636:636
      #- 636:636/udp
    restart: "unless-stopped"
    secrets:
      - ldap_admin_password
      - ldap_readonly_password
    networks:
      - defaultNet

  wordpress:
    build:
      context: ./Build_Apache
      dockerfile: Dockerfile
    image: wp_custom
    container_name: wordpress
    environment:
      - WP_ADMIN_PASSWORD=/run/secrets/wp_admin_password
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    links:
      - "mysql:mysql"
      - "ldap:ldap"
    depends_on:
      - mysql
    restart: "unless-stopped"
    secrets:
      - wp_admin_password
    networks:
      - defaultNet

  py_import:
    container_name: py_import
    image: py_import:latest
    volumes: 
      - ./db:/app
    networks:
      - defaultNet

secrets:
  mysql_root_password:
    file: ./Secrets/mysql_root_password.txt
  ldap_admin_password:
    file: ./Secrets/ldap_admin_password.txt
  ldap_readonly_password:
    file: ./Secrets/ldap_readonly_password.txt
  wp_admin_password:
    file: ./Secrets/wp_admin_password.txt


volumes:
  mysql_data:
    name: "mysql_data"
  ldap_data:
    name: "ldap_data"
  ldap_conf:
    name: "ldap_conf"

networks:
  defaultNet:
    name: "defaultNet"
  localNet:
    name: "localNet"