services: 
  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_db:/docker-entrypoint-initdb.d/
    env_file:
      - .env
    ports:
      - 3306:3306
    restart: "unless-stopped"
  
  ldap:
    image: osixia/openldap
    container_name: ldap
    volumes:
      - ldap_conf:/etc/ldap/slapd.d
      - ldap_data:/var/lib/ldap
    env_file:
      - .env
    ports:
      - 389:389
      - 389:389/udp
      - 636:636
      - 636:636/udp
    restart: "unless-stopped"

  wordpress:
    image: wp_custom:latest
    container_name: wordpress
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    links:
      - "mysql:mysql"
      - "ldap:ldap"
    depends_on:
      - mysql
    restart: "unless-stopped"

volumes:
  mysql_data:
    name: "mysql_data"
    external: false
  ldap_data:
    name: "ldap_data"
    external: false
  ldap_conf:
    name: "ldap_conf"
    external: false